services:
  dcss:
    image: ghcr.io/nkhoit/dcss-webtiles:latest
    container_name: dcss-webtiles
    ports:
      - "8080:8080"
    volumes:
      - dcss-data:/data
    restart: unless-stopped

volumes:
  dcss-data:
